pipeline {
    agent any
  
    environment {
        DOCKER_IMAGE = 'houaidamang/mon-app'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        DOCKER_FULL_IMAGE = "${DOCKER_IMAGE}:${DOCKER_TAG}"
    }
    
    stages {
        stage('Cloner le dépôt') {
            steps {
                git branch: 'docker', 
                    url: 'https://github.com/houaida-mangour/tp3-k8s/tree/main'
            }
        }
 }
        stage('Construire l\'image Docker') {
            steps {
                script {
                    sh "docker build -f Docker-files/app/Dockerfile -t ${DOCKER_FULL_IMAGE} ."
                    sh "docker tag ${DOCKER_FULL_IMAGE} ${DOCKER_IMAGE}:latest"
                }
            }
        }
        
        stage('Pousser l\'image Docker') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        passwordVariable: 'DOCKER_PASSWORD',
                        usernameVariable: 'DOCKER_USERNAME'
                    )]) {
                        // Use --password-stdin for security
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                        sh "docker push ${DOCKER_FULL_IMAGE}"
                        sh "docker push ${DOCKER_IMAGE}:latest"
                    }
                }
            }
        }
        stage('Déployer dans Kubernetes') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'kubeconfig-docker-desktop', variable: 'KUBECONFIG')]) {
                        sh 'kubectl --kubeconfig=$KUBECONFIG get nodes'
                        
                        // Appliquer les manifestes Kubernetes
                        //sh "kubectl --kubeconfig=$KUBECONFIG set image deployment/mon-app mon-app=${DOCKER_FULL_IMAGE} -n default || true"
                        
                        // Ou appliquer des fichiers de déploiement
                        //sh 'kubectl --kubeconfig=$KUBECONFIG apply -f k8s/ -n default'
                        
                        // Vérifier le statut du déploiement
                        //sh 'kubectl --kubeconfig=$KUBECONFIG rollout status deployment/mon-app -n default'
                    }
                }
            }
    }
    
   
}