pipeline {
    agent any
    environment {
        IMAGE_NAME = "houaidamang/nodejs-app"
        IMAGE_TAG  = "latest"
        FULL_IMAGE = "${IMAGE_NAME}:${IMAGE_TAG}"
    }
    stages {
        stage('Cloner le dépôt') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/houaida-mangour/tp3-k8s.git'
            }
        }
        stage('Build Docker image') {
            steps {
                script {
                    sh "docker build -t ${FULL_IMAGE} ."
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub', 
                        usernameVariable: 'DOCKER_USER', 
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${FULL_IMAGE}
                        """
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh "kubectl apply -f deployment.yaml"
                    sh "kubectl apply -f service.yaml"
                }
            }
        }
    }
    post {
        success {
            echo "Déploiement réussi ! Accède via NodePort."
            sh "kubectl get svc nodejs-service"
        }
    }
}
